server:
  port: 8082

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "admin123"
  dbname: "postgres"
  schema: "go_restaurant_orders_order_service"
  sslmode: "disable"
rabbitmq:
  url: "amqp://admin:admin123@localhost:5672/"
  exchange: "order_status_exchange"
  queue: "order_status_queue"
  routing_key: "order.status"
menu_service:
  connect_timeout: 5
  base_url: "http://localhost:8081"
  endpoint:
    get_dish_by_id: "/dishes/:id"
auth_service:
  connect_timeout: 5
  base_url: "http://localhost:8080"
  endpoint:
    get_user_by_id: "/users/:id"